version: '2.0'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-db:
    image: crs4/i2b2-postgres-db
    container_name: §§INSTANCE-db
    restart: unless-stopped
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: §§POSTGRES_PASSWORD
       POSTGRES_DB: i2b2
    ports:
      - "5432:5432"
    volumes_from: 
      - §§INSTANCE-db-data
    depends_on:
      - §§INSTANCE-db-data
    networks:
      - bibbox-default-network

  §§INSTANCE-i2b2-server:
    image: crs4/i2b2-server:1708b
    container_name: §§INSTANCE-i2b2-server
    restart: unless-stopped
    environment:
      JBOSS_IMAGE: crs4/jboss_wildfly:10.0.0.Final
      i2b2_VERSION_SHORT: 1708b
      i2b2_VERSION: 1.7.8b
    ports:
      - "§§PORT1:9090"
      - "§§PORT2:9990"
      - "§§PORT3:9009"
      - "§§PORT4:8080"
    links:
      - §§INSTANCE-db
    networks:
      - bibbox-default-network

  §§INSTANCE-i2b2-www:
    image: crs4/i2b2-www
    container_name: §§INSTANCE-i2b2-www
    ports:
      - "§§PORT:80"
    networks:
      - bibbox-default-network

  §§INSTANCE-db-data:
    image: busybox
    container_name: §§INSTANCE-db-data
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
