version: '2.0'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-db:
    container_name: §§INSTANCE-db
    restart: unless-stopped
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: i2b2
    build:
       context: ./i2b2postgresdb
       dockerfile: Dockerfile
       args:
           I2B2NODE: §§INSTANCE-i2b2-server
    volumes_from: 
      - §§INSTANCE-db-data
    depends_on:
      - §§INSTANCE-db-data
    networks:
      bibbox-default-network:


  §§INSTANCE-i2b2-server:
    container_name: §§INSTANCE-i2b2-server
    restart: unless-stopped
    environment:
      JBOSS_IMAGE: crs4/jboss_wildfly:10.0.0.Final
      i2b2_VERSION_SHORT: 1708b
      i2b2_VERSION: 1.7.8b
    build:
       context: ./i2b2server
       dockerfile: Dockerfile
       args:
           I2B2NODE: §§INSTANCE-i2b2-server
           DBNODE: §§INSTANCE-db
    ports:
      - "§§APORT:9090"
      - "§§BPORT:9990"
      - "§§CPORT:9009"
      - "§§DPORT:8080"
    depends_on:
      - §§INSTANCE-db
    networks:
       bibbox-default-network:


  §§INSTANCE-i2b2-www:
    container_name: §§INSTANCE-i2b2-www
    ports:
      - "§§PORT:80"
    build:
       context: ./i2b2www
       dockerfile: Dockerfile
       args:
          I2B2NODE: §§INSTANCE-i2b2-server
    depends_on:
      - §§INSTANCE-i2b2-server
    networks:
       bibbox-default-network:


  §§INSTANCE-db-data:
    image: busybox
    container_name: §§INSTANCE-db-data
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
